planning terraform

diff --git a/.github/workflows/sandbox.yml b/.github/workflows/sandbox.yml
--- a/.github/workflows/sandbox.yml
+++ b/.github/workflows/sandbox.yml
@@ -25,6 +25,7 @@ jobs:
     name: generate-env-file
     # needs: [push-build]
     runs-on: ubuntu-latest
+    if : github.ref == "refs/heads/staging"
     steps:
     - name: chechkout
       uses: actions/checkout@v2
@@ -103,7 +104,6 @@ jobs:
         echo "DB_NAME=$DB_NAME" >> .env
         echo "DB_PASS=$DB_PASS" >> .env
         echo "DB_PASSWORD=$DB_PASSWORD" >> .env
-        echo "DB_URL=$DB_URL" >> .env
         echo "DB_USER_NAME=$DB_USER_NAME" >> .env
         echo "DEFAULT_ELECTRICITY_PROVIDER=$DEFAULT_ELECTRICITY_PROVIDER" >> .env
         echo "DEPLOYMENT_PREFIX=$DEPLOYMENT_PREFIX" >> .env
@@ -114,7 +114,6 @@ jobs:
         echo "IRECHARGE_PUBLIC_KEY=$IRECHARGE_PUBLIC_KEY" >> .env
         echo "IRECHARGE_VENDOR_CODE=$IRECHARGE_VENDOR_CODE" >> .env
         echo "JWT_SECRET=$JWT_SECRET" >> .env
-        echo "KAFKA_INSTANCE_TYPE=$KAFKA_INSTANCE_TYPE" >> .env
         echo "LOAD_TEST_MODE=$LOAD_TEST_MODE" >> .env
         echo "LOGO_URL=$LOGO_URL" >> .env
         echo "NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME" >> .env
@@ -141,127 +140,164 @@ jobs:
     - name: push to state to s3
       run: |
         aws s3 cp ./.env s3://accuvend-bucket-configuration/ 
+    - name: Save env file
+      uses: actions/cache@v2
+      with:
+        path: ./.env
+        key: env-file
       
-  # scan-backend: 
-  #   name: scan-backend
-  #   runs-on: ubuntu-latest
-  #   # needs: [test-backend]
-  #   steps: 
-  #     - name: Checkout
-  #       uses: actions/checkout@v2
-  #     - uses: actions/setup-node@v4
-  #       with:
-  #         node-version: 18
-  #     - run: npm ci
-  #     - run: npm audit fix --force
-  #     - run: npm audit fix --audit-level=critical --force
-  #     - run: npm audit --audit-level=critical
-  #     - name: Save nodemodules cache
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: node_modules
-  #         key: backend-build
+  scan-backend: 
+    name: scan-backend
+    runs-on: ubuntu-latest
+    if : github.ref == "refs/heads/staging"
+    # needs: [test-backend]
+    needs: [generate-env-file]
+    steps: 
+      - name: Checkout
+        uses: actions/checkout@v2
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
+      - run: npm ci
+      - run: npm audit fix --force
+      - run: npm audit fix --audit-level=critical --force
+      - run: npm audit --audit-level=critical
+      - name: Save nodemodules cache
+        uses: actions/cache@v2
+        with:
+          path: node_modules
+          key: backend-build
 
         
-  # build-backend:
-  #   name: build-backend
-  #   needs: [scan-backend]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v2
-  #     - name: Restore frontend cache
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: node_modules
-  #         key: backend-build
-  #     - uses: actions/setup-node@v4
-  #       with:
-  #         node-version: 20
-  #     - name: Back-end build
-  #       run: |
-  #         ls
-  #         rm -rf dist
-  #         npm install
-  #         npm run build
-  #         ls ./src/utils/Email/templates && cp -r src/utils/Email/templates/ dist/utils/Email/  && rm -f ./dist/utils/Email/templates/index.ts  && ls ./dist/utils/Email/templates
-  #     - name: cache dist 
-  #       uses: actions/checkout@v2
-  #       with:
-  #         path: dist
-  #         key: dist-folder
-  #     - run: |
-  #         tsc --version
+  build-backend:
+    name: build-backend
+    needs: [scan-backend]
+    if : github.ref == "refs/heads/staging"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Restore frontend cache
+        uses: actions/cache@v2
+        with:
+          path: node_modules
+          key: backend-build
+      - name: Restore env file
+        uses: actions/cache@v2
+        with:
+          path: ./.env
+          key: env-file
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Back-end build
+        run: |
+          ls
+          rm -rf dist
+          npm install
+          npm run build
+          cp .env dist/.env
+          ls ./src/utils/Email/templates && cp -r src/utils/Email/templates/ dist/utils/Email/  && rm -f ./dist/utils/Email/templates/index.ts  && ls ./dist/utils/Email/templates
+      - name: cache dist 
+        uses: actions/checkout@v2
+        with:
+          path: dist
+          key: dist-folder
+      - run: |
+          tsc --version
          
         
-  # push-build:
-  #   name: push-build
-  #   needs: [build-backend]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: chechkout
-  #       uses: actions/checkout@v2
-  #     - name: restore dist 
-  #       uses: actions/checkout@v2
-  #       with:
-  #         path: dist
-  #         key: dist-folder
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
-  #         aws-region: eu-west-2
-  #     - name: push to state to s3
-  #       run: |
-  #         zip -r dist.zip dist
-  #         aws s3 cp ./dist.zip s3://staging-bucket-deployment/ 
+  push-build:
+    name: push-build
+    needs: [build-backend]
+    if : github.ref == "refs/heads/staging"
+    runs-on: ubuntu-latest
+    steps:
+      - name: chechkout
+        uses: actions/checkout@v2
+      - name: restore dist 
+        uses: actions/checkout@v2
+        with:
+          path: dist
+          key: dist-folder
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
+          aws-region: eu-west-2
+      - name: push to state to s3
+        run: |
+          zip -r dist.zip dist
+          aws s3 cp ./dist.zip s3://staging-bucket-deployment/ 
         
       
-  # create-update-environment:
-  #   name: create-environment
-  #   needs: [build-backend]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v2
-  #   - name: Configure AWS Credentials 2
-  #     uses: aws-actions/configure-aws-credentials@v4
-  #     with:
-  #       aws-region: eu-west-2
-  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
-  #   - name: pull terraform state from s3
-  #     run: |
-  #       aws s3 cp s3://sandbox-terraform-item/terraform.tfstate ./terraform/sandbox && echo "Success: The AWS CLI command completed successfully." || echo "Error: The AWS CLI command failed."
+  create-update-environment:
+    name: create-environment
+    needs: [build-backend]
+    if : github.ref == "refs/heads/staging"
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Configure AWS Credentials 2
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-region: eu-west-2
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
+    - name: pull terraform state from s3
+      run: |
+        aws s3 cp s3://sandbox-terraform-item/terraform.tfstate ./terraform/sandbox && echo "Success: The AWS CLI command completed successfully." || echo "Error: The AWS CLI command failed."
     
-  #   - name: Terraform Init
-  #     uses: hashicorp/terraform-github-actions/init@v0.4.0
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       TF_ACTION_WORKING_DIR: 'terraform/sandbox'
-  #       TF_AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       TF_AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #       TF_region: "eu-west-2"
-  #       TF_subnet_1: "10.0.0.0/24"
-  #       TF_subnet_2: "10.0.1.0/24"
-  #       TF_subnet_3: "10.0.2.0/24"
-  #       TF_accountId: "984109170193"
-  #       TF_image_id: "ami-0e5f882be1900e43b"
-  #       TF_instance_type: "r6gd.xlarge"
-  #       kafka_instance_type: "kafka.t3.small"
-  #       instance_keypair: "production-key-pair"
-  #       db_instance_type: "db.t3.micro"
+    - name: Terraform Setup
+      uses: hashicorp/setup-terraform@v3
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        TF_ACTION_WORKING_DIR: 'terraform/sandbox'
+        TF_AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
+        TF_AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        TF_VAR_region: "eu-west-2"
+        TF_VAR_subnet_1: ${{secrets.SUBNET_1}}
+        TF_VAR_subnet_2: ${{secrets.SUBNET_2}}
+        TF_VAR_subnet_3: ${{secrets.SUBNET_3}}
+        TF_VAR_accountId: ${{secrets.ACCOUNTID}}
+        TF_VAR_image_id: ${{secrets.IMAGE_ID}}
+        TF_VAR_instance_type: ${{secrets.INSTANCE_TYPE}}
+        TF_VAR_kafka_instance_type: "kafka.t3.small"
+        TF_VAR_instance_keypair: "sandbox-key-pair"
+    - name: change directory to sanbox
+      run: cd terraform/sandbox
+      
+    - name: Terraform fmt
+      id: fmt
+      run: terraform fmt -check
+      continue-on-error: true
 
-    # - name: Terraform Validate
-    #   uses: hashicorp/terraform-github-actions/validate@v0.3.7
+    - name: Terraform Init
+      id: init
+      run: terraform init
+    
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate -no-color
+    
+    - name: Terraform Plan
+      id: plan
+      run: terraform plan -no-color
+      continue-on-error: true
 
-    # - name: Terraform Apply
-    #   uses: hashicorp/terraform-github-actions/apply@v0.4.0
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #     TF_ACTION_WORKING_DIR: 'terraform/sandbox'
-    #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-    #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #     TF_db_password: ${{secrets.DB_PASSWORD}}
+    - name: Save tft.state file 
+      run: |
+          pwd
+          aws s3 cp terraform.tfstate s3://sandbox-terraform-item/
+      
+    - run: echo ${{ steps.plan.outputs.stdout }}
+    - run: echo ${{ steps.plan.outputs.stderr }}
+    - run: echo ${{ steps.plan.outputs.exitcode }}
+      
+
+    
       
